# Generated by Django 3.0.8 on 2020-08-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Folder', max_length=20, null=True)),
                ('details', models.TextField(null=True)),
                ('tags', models.ManyToManyField(to='Notes.Tags')),
            ],
        ),
    ]
