# Generated by Django 3.0.8 on 2020-08-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_auto_20200825_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folders',
            name='root',
            field=models.ForeignKey(blank=True, default='root', null=True, on_delete=django.db.models.deletion.CASCADE, to='Notes.Folders'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Notes.Tags'),
        ),
    ]
