# Generated by Django 3.0.8 on 2020-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_auto_20200825_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
