# Generated by Django 3.0.8 on 2020-08-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Notes.Folders'),
        ),
    ]
