# Generated by Django 3.0.8 on 2020-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_notes_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(blank=True, default='<div class="cell-row"><div class="cell-column" contenteditable></div></div>', null=True),
        ),
    ]
