# Generated by Django 3.0.8 on 2020-09-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_auto_20200831_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='name',
            field=models.CharField(default='New Folder', max_length=100, null=True),
        ),
    ]
