# Generated by Django 3.0.8 on 2020-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weekday', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
    ]
