# Generated by Django 3.0.8 on 2020-10-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleobject',
            name='links',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
